### ISSUE TITLE
Fails with perls up to 5.24.0 due use of postfix dereferencing

### ISSUE THREAD

**Issue by andk** [Humanstate/cron-sequencer#1]
As persubject. Sample fail report: http://www.cpantesters.org/cpan/report/c13f7f40-d508-11ec-b6db-826572b253f2

Diagnostics:

Error:  syntax error at /tmp/loop_over_bdir-2267-p9mRYy/Cron-Sequencer-0.01-0/blib/lib/Cron/Sequencer/Parser.pm line 45, near "->@*"

**Comment by nwc10** [comment]
Thanks for the bug report. I was already aware of this bug thanks to the CPAN smokers you run, so thanks also for that. :-)

However, I seem to be having a bit of a https://xkcd.com/349/ day.

I think that the fix is 2 lines (in the right place) but in trying to replicate this I've hit

- failure to reliably build `IPC::Run3` on my (work) machine with v5.20.0 (cause now located - it's the generated `Errno.pm`)
- a bug in git bisect when given revision start end points expressed as `v5.20.0` and `v5.22.0`
- swamping the network to the (work) machine sufficient that I needed to plug the "console" in (which means moving the lawn mower out of the way to get to it...)
- and I think at least one more thing that I've lost track of in the chaos

But that list of "aargh" is starting to get shorter again. And "plugging the console in" needed to be done at some point soonish because it needed a kernel update, so that got that done too...

**Comment by nwc10** [comment]
http://www.cpantesters.org/cpan/report/6384d362-d5e1-11ec-841b-e0b4af205130 -- `PASS Cron-Sequencer-0.02 5.20.3 GNU/Linux`

**Comment by nwc10** [comment]
> * a bug in git bisect when given revision start end points expressed as `v5.20.0` and `v5.22.0`

For reference, the bug was git/git@27257bc466 and fixed as git/git@7730f85594d4595605934e39d1d816ab663d8fa8
